# Generated by Django 3.0.3 on 2021-08-25 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball_tournament.Team'),
        ),
    ]
